'''版本号'''
__version__ = '0.1.0'
'''作者'''
__author__ = 'Charles'
'''标题'''
__title__ = 'codefree'
'''描述'''
__description__ = 'CodeFree: Make no code a reality.'
'''链接'''
__url__ = 'https://github.com/CharlesPikachu/codefree'
'''邮件'''
__email__ = 'charlesblwx@gmail.com'
'''license'''
__license__ = 'Apache License 2.0'